---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

library(htmlwidgets)
```

<!-- Setting up dataframe and filtering it out. -->

```{r, message=FALSE, warning=FALSE, echo=FALSE}
data("rest_inspec")

rest_inspec =
  rest_inspec %>% 
  select(inspection_date, boro, dba, cuisine_description, action, grade, score, critical_flag) %>% 
  filter(
    action == c("Violations were cited in the following area(s)", "No violations were recorded at the time of this inspection", "Establishment Closed by DOHMH.  Violations were cited in the following area(s) and those requiring immediate action were addressed.")) %>% 
      drop_na(score)
```


Column {data-width=700}
-----------------------------------------------------------------------

[back to homepage](https://salnel97.github.io/index.html)\

### A bar plot showing the number of inspections per restaurant cuisine type

```{r, message=FALSE, warning=FALSE, echo=FALSE}

rest_inspec %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(
    x = ~cuisine_description,
    y = ~n,
    alpha = .5,
    type = "bar",
    mode = "markers",
    colors = "viridis") %>% 
  layout(xaxis = list(title = ' ', tickangle = 45),
         yaxis = list(title = 'Count'),
         width = 1250,
         height = 500,
         margin = list(b = 160, l = 50),
         showlegend = FALSE)

```

Column {data-width=300}
-----------------------------------------------------------------------

### A box plot showing the average inspection score per borough

```{r, message=FALSE, warning=FALSE, echo=FALSE}

rest_inspec %>% 
  plot_ly(
    x = ~boro,
    y = ~score,
    color = ~boro,
    alpha = .5,
    type = "box",
    mode = "markers",
    colors = "viridis") %>% 
  layout(xaxis = list(title = 'Borough'),
         yaxis = list(title = 'Inspection Score'),
         showlegend = FALSE)

```

### Scatter plot of inspection score as a function of inspection date

```{r, message=FALSE, warning=FALSE, echo=FALSE}

rest_inspec %>% 
  mutate(label = str_c("Score: ", score)) %>% 
  plot_ly(
    x = ~inspection_date,
    y = ~score,
    color = ~critical_flag,
    text = ~label,
    alpha = .5,
    type = "scatter",
    mode = "markers") %>% 
   layout(xaxis = list(title = 'Inspection Date'),
         yaxis = list(title = 'Inspection Score'),
         showlegend = FALSE)
  
```

